
#!/bin/sh
set -eu

echo "[START] FreeSWITCH provisioning script"

FS_CONF_DIR="${FS_CONF_DIR:-/etc/freeswitch}"


need() {
  k="$1"
  eval v="\${$k}"
  if [ "x$v" = "x" ]; then
    echo "Missing env: $k" >&2
    exit 1
  fi
}

# Required env vars
need SIP_USER
need SIP_PASSWORD
need SIP_DOMAIN
need PROVIDER_HOST
need PROVIDER_PORT
need PROVIDER_USERNAME
need PROVIDER_PASSWORD
need PROVIDER_TRANSPORT
need EXTERNAL_IP

# Paths
DIR_DEFAULT="$FS_CONF_DIR/directory/default"
DP_DEFAULT="$FS_CONF_DIR/dialplan/default"
GW_DIR="$FS_CONF_DIR/sip_profiles/external"
VARS_XML="$FS_CONF_DIR/vars.xml"
VARS_LOCAL="$FS_CONF_DIR/vars_local.xml"

mkdir -p "$DIR_DEFAULT" "$DP_DEFAULT" "$GW_DIR"


# 1) Create SIP user (directory)
USER_XML="$DIR_DEFAULT/${SIP_USER}.xml"

cat > "$USER_XML" <<EOF
<include>
  <user id="${SIP_USER}">
    <params>
      <param name="password" value="${SIP_PASSWORD}"/>
      <param name="dial-string" value="{sip_invite_domain=${SIP_DOMAIN}}sofia/internal/\${destination_number}@\${domain_name}"/>
    </params>
    <variables>
      <variable name="user_context" value="default"/>
      <variable name="effective_caller_id_name" value="${SIP_USER}"/>
      <variable name="effective_caller_id_number" value="${SIP_USER}"/>
    </variables>
  </user>
</include>
EOF
echo "[STEP] User XML block done."

# Output and check if user file was created
if [ -f "$USER_XML" ]; then
  echo "[OK] User XML created: $USER_XML"
  echo "--- $USER_XML ---"
  cat "$USER_XML"
  echo "-----------------"
else
  echo "[ERROR] User XML was NOT created: $USER_XML" >&2
fi
echo "[STEP] User XML check done."

# 2) Create Provider Gateway
GW_XML="$GW_DIR/provider.xml"
cat > "$GW_XML" <<EOF
<include>
  <gateway name="provider">
    <param name="proxy" value="${PROVIDER_HOST}"/>
    <param name="port" value="${PROVIDER_PORT}"/>
    <param name="username" value="${PROVIDER_USERNAME}"/>
    <param name="password" value="${PROVIDER_PASSWORD}"/>
    <param name="register" value="true"/>
    <param name="transport" value="${PROVIDER_TRANSPORT}"/>
    <param name="caller-id-in-from" value="true"/>

    <!-- Часто полезно для NAT -->
    <param name="retry-seconds" value="30"/>
    <param name="expire-seconds" value="600"/>
  </gateway>
</include>
EOF
echo "[STEP] Provider Gateway block done."

# 3) Dialplan: any call to SIP_USER goes to provider
DP_XML="$DP_DEFAULT/forward_${SIP_USER}.xml"
cat > "$DP_XML" <<EOF
<include>
  <extension name="forward_${SIP_USER}_to_provider">
    <condition field="destination_number" expression="^${SIP_USER}$">
      <!-- Проброс caller id и номера как есть -->
      <action application="set" data="hangup_after_bridge=true"/>
      <action application="set" data="continue_on_fail=true"/>
      <action application="bridge" data="sofia/gateway/provider/${destination_number}"/>
    </condition>
  </extension>
</include>
EOF
echo "[STEP] Dialplan block done."

# 4) external ip override
cat > "$VARS_LOCAL" <<EOF
<include>
  <!-- generated by provision_freeswitch.sh -->
  <X-PRE-PROCESS cmd="set" data="external_sip_ip=${EXTERNAL_IP}"/>
  <X-PRE-PROCESS cmd="set" data="external_rtp_ip=${EXTERNAL_IP}"/>
</include>
EOF
echo "[STEP] External IP block done."

# 5) Ensure vars.xml includes vars_local.xml
# Try to insert before closing </include>. If not present, append safely.
if grep -q "vars_local.xml" "$VARS_XML" 2>/dev/null; then
  echo "[STEP] vars_local.xml already included in vars.xml."
else
  if grep -q "</include>" "$VARS_XML" 2>/dev/null; then
    # insert before last </include>
    sed -i '0,/<\/include>/{s/<\/include>/<\!-- include local overrides --\>\n  <X-PRE-PROCESS cmd="include" data="vars_local.xml"\/>\n<\/include>/}' "$VARS_XML" \
      || echo "Could not auto-edit vars.xml; include vars_local.xml manually." >&2
    echo "[STEP] Added vars_local.xml include to vars.xml."
  else
    # If vars.xml is unusual, just append include directive line
    echo '<X-PRE-PROCESS cmd="include" data="vars_local.xml"/>' >> "$VARS_XML"
    echo "[STEP] Appended vars_local.xml include to vars.xml."
  fi
fi


# Final summary check
echo "[STEP] Final file existence check..."
fail=0
for f in "$USER_XML" "$GW_XML" "$DP_XML" "$VARS_LOCAL"; do
  if [ -f "$f" ]; then
    echo "[OK] $f exists."
  else
    echo "[ERROR] $f is missing!" >&2
    fail=1
  fi
done

if [ "$fail" -eq 0 ]; then
  echo "[SUCCESS] All config files generated successfully."
else
  echo "[FAIL] Some config files are missing. Check previous errors."
fi

echo "[DONE] Provisioning script complete."

# Optionally reload if fs_cli exists
if command -v fs_cli >/dev/null 2>&1; then
  fs_cli -x reloadxml || true
  fs_cli -x "sofia profile external restart" || true
fi
